# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound
        rectangle:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound



