# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        rectangle:
            quality: 75
            filters:
                thumbnail:
                    size: [2400, 1800]
                    mode: outbound
        cercle:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 150]
                    mode: outbound
        carre:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound




